KAFKA_HOSTS = "***REMOVED***"
REDIS_HOST = "localhost"

KAFKA_TOPIC = "traptor.***REMOVED***1"

APIKEYS = {}
APIKEYS['CONSUMER_KEY'] = "***REMOVED***"
APIKEYS['CONSUMER_SECRET'] = "***REMOVED***"
APIKEYS['ACCESS_TOKEN'] = "***REMOVED***"
APIKEYS['ACCESS_TOKEN_SECRET'] = "***REMOVED***"

TRAPTOR_ID = 0
TRAPTOR_TYPE = 'follow'