KAFKA_HOSTS = "***REMOVED***"

KAFKA_TOPIC = "traptor.***REMOVED***1"

APIKEYS[CONSUMER_KEY] = "***REMOVED***"
APIKEYS[CONSUMER_SECRET] = "***REMOVED***"
APIKEYS[ACCESS_TOKEN] = "***REMOVED***"
APIKEYS[ACCESS_TOKEN_SECRET] = "***REMOVED***"

TRACK_RULES = []

FOLLOW_RULES = []